# default theme at https://github.com/asciidoctor/asciidoctor-pdf/blob/master/data/themes/default-theme.yml
#https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/pdf-non-latin-languages
extends: default
font:
  fallbacks:
    - kaigen-gothic-tw
  catalog:
    # These are the KaiGen Gothic CN fonts, download them from
    # https://github.com/minjiex/kaigen-gothic/tree/master/dist/CN
    kaigen-gothic-tw:
      normal: KaiGenGothicTW-Regular.ttf
      bold: KaiGenGothicTW-Bold.ttf
      italic: KaiGenGothicTW-Regular.ttf
      bold_italic: KaiGenGothicTW-Bold.ttf
base:
  font_family: kaigen-gothic-tw